### ISSUE TITLE
Package errors

### ISSUE THREAD

**Issue by wiegeabo** [wiegeabo/MSE_STAW_Templates#6]
After opening a STAW card set, the following error appears, sometimes multiple times.

File not found: '' in package 'C:\MSE\data\staw-upgrade.mse-style'
If you are trying to open a file from another package, use "/package/filename"

**Comment by wiegeabo** [comment]
No functions seem to be hampered. Unsure what's causing this.

**Comment by wiegeabo** [comment]
Could be related to choice blocks referencing a 'none' option without a corresponding 'none"' without a filename a script?

**Comment by Strormer** [comment]
I believe this is related to the card set info that's supposed to show up in the list area in MSE. I never could get that to work correctly, but it's the only function in the base MSE template that seems to be not functioning as intended.

**Comment by wiegeabo** [comment]
I’ve kind of tracked it down. I noticed that if I remove the sub faction code from the offending file, the errors don’t appear.

So it seems like there’s an issue with that code, or the code around it.

**Comment by Strormer** [comment]
I see. Yeah, I'm not really sure what I did wrong in that case. I posted it ([here](https://magicseteditor.boards.net/thread/1400/custom-template-help)) in hopes someone would enlighten me.

Incidentally, I also cleaned up some of the code and files to have a cleaner package before I shared it on the forum. I've saved a zip of the files in the same GoogleDrive folder I have the new icons in. Feel free to use or disregard, as you choose, it's just the version I have installed for myself. 

And thank you for picking up this project and moving it forward. It's really helped get me excited about the game again. I probably won't have as much time to work on it as I managed this weekend, but I'll definitely keep involved as much as I can.

**Comment by Strormer** [comment]
I got all of these issues fixed in the updated version (linked in the Squadron type issue). Turns out it was all the "None" selections where there was no listed image. I just added a "blank.png" to each so they would resolve correctly and they've all disappeared. This also appears to have had the incidental benefit of slightly speeding up the maneuver card type.

**Comment by wiegeabo** [comment]
I'm not sure why, but I can't download the zip file. It just says it can't
find it when I click download.

[image: image.png]

**Comment by Strormer** [comment]
I changed the sharing permissions on the file in my Google Drive. You should have full access now. If that doesn't work, then I'm not sure what's happening.

**Comment by wiegeabo** [comment]
I figure it out. I think the problem was it was a large zip file. I had to install zip extractor to my drive so I could extract the files to my drive location.

**Comment by wiegeabo** [comment]
Ensuring "blank:" points to an image fixes the issue.

Each folder now has a blank.png file and the "blank:" entries should point to those.
